COMPONENT_DEPENDS	:= Storage
COMPONENT_INCDIRS	:= src/include
COMPONENT_SRCDIRS	:= src
COMPONENT_DOXYGEN_INPUT := src/include

COMPONENT_VARS			+= DISK_MAX_SECTOR_SIZE
DISK_MAX_SECTOR_SIZE	?= 512
GLOBAL_CFLAGS			+= -DDISK_MAX_SECTOR_SIZE=$(DISK_MAX_SECTOR_SIZE)
